DROP TABLE IF EXISTS rank;
CREATE TABLE post (
	  id INTEGER PRIMARY KEY AUTOINCREMENT,
	  player_name TEXT NOT NULL,
	  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  score INTEGER NOT NULL
);
